/* DO NOT EDIT THIS FILE - it is machine generated */
#include </opt/java/11.0.14/include/jni.h>
/* Header for class net_autonav_Subsystems_System_RobotCommunicator */

#ifndef _Included_net_autonav_Subsystems_System_RobotCommunicator
#define _Included_net_autonav_Subsystems_System_RobotCommunicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_autonav_Subsystems_System_RobotCommunicator
 * Method:    sendJoystickMovement
 * Signature: (CF)V
 */
JNIEXPORT void JNICALL Java_net_autonav_Subsystems_System_RobotCommunicator_sendJoystickMovement
  (JNIEnv *, jclass, jchar, jfloat);

/*
 * Class:     net_autonav_Subsystems_System_RobotCommunicator
 * Method:    subscribeRobotEvents
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_autonav_Subsystems_System_RobotCommunicator_subscribeRobotEvents
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     net_autonav_Subsystems_System_RobotCommunicator
 * Method:    setRobotController
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_autonav_Subsystems_System_RobotCommunicator_setRobotController
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
