package net.autonav.Enums;

public enum Commands {
    CHANGE_HEADING,
    CHANGE_VELOCITY,
    GET_OBJECT_DISTANCE,
    GET_OBJECT_HEADING,
    GET_OBJECT_VELOCITY,
    GET_ROBOT_HEADING,
    GET_ROBOT_VELOCITY,
    GET_LIDAR_RAW
}
